services:
  postgres:
    image: postgres:17
    container_name: analytics-postgres
    environment:
      POSTGRES_DB: analytics_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/migrations:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: analytics-redis
    ports:
      - "6376:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: